#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Get videos from the internet.

Channel=${1:-lrt}
Start_time=${2:-now}
Duration=${3:-60m}
      Tracks="hls-audio1-ORG+hls-audio1-LIT+hls-3"
Audio_tracks="hls-audio1-ORG+hls-audio1-LIT"
      Output="%(title)s [%(id)s].%(ext)s"
Audio_output="%(title)s [%(id)s]-audio.%(ext)s"
Curr_date=$(date +%Y-%m-%d)
Curr_time=$(date +%H:%M:%S)
Chan_suffix=$(echo ${Channel} | awk '{print toupper($0)}')

case $Channel in

  (lrt)
    Url="https://www.lrt.lt/mediateka/tiesiogiai/lrt-televizija"
    ;;

  (lrt+)
    Url="https://www.lrt.lt/mediateka/tiesiogiai/lrt-plius"
    ;;

  (*)
    Url="TODO://unknown-channel"
    ;;
esac

      Log=${4:-[YEAR]-ORIG-(ENG;-LITH)-${Curr_time}-FHD.${Curr_date}-${Chan_suffix}}.log
Audio_log=${4:-[YEAR]-ORIG-(ENG;-LITH)-${Curr_time}-FHD.${Curr_date}-${Chan_suffix}}audio.log

dump ()
{
cd
at "${Start_time}" << \
-----------------------------
(
  date
  pwd
  timeout -s SIGINT         \
    ${Duration}             \
    yt-dlp                  \
      --audio-multistreams  \
      -f "${Tracks}"        \
      -o "${Output}"        \
      ${Url}                \

) \
> "${Log}" 2>&1
-----------------------------
}

dump

echo "Using some defaults:"
echo "$Cmd"
